$(".eng").show();
$(".tr").hide();
$(".tr1").hide();
$(".eng1").show();
$(".tr-img").hide();
$(".eng-img").show();
$(".eng1").click(function(){
    $(".eng").show();
    $(".tr").hide();
    $(".tr1").show();
    $(".eng1").hide();
    $(".tr-img").show();
    $(".eng-img").hide();
});
$(".tr1").click(function(){
    $(".tr").show();
    $(".eng").hide();
    $(".tr1").hide();
    $(".eng1").show();
    $(".tr-img").hide();
    $(".eng-img").show();
});